version: '3.3'
# Define services
services:
# App backend service
  notificationsvc:
# Configuration for building the docker image for the backend service
    build: notificationservice
    container_name: notificationservice
    image: hotelbookingapp/notificationservice:1.0.0
    ports:
    - "8082:8082" # Forward the exposed port 8082 to port 8082 on the host machine
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 3.235.176.185
    depends_on:
      - serviceregistry # This service depends on serviceregistry. Start that first.
  paymentsvc:
    build: paymentservice
    container_name: paymentservice
    image: hotelbookingapp/paymentservice:1.0.0
    ports:
    - "8083:8083" # Map the exposed port 3000 on container to port 3000 on the host machine
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 3.235.176.185
    depends_on:
      - serviceregistry # This service depends on serviceregistry. Start that first.
# Frontend Service
  bookingsvc:
    build: bookingservice
    container_name: bookingservice
    image: hotelbookingapp/bookingservice:1.0.0
    ports:
    - "8080:8080" # Map the exposed port 8080 on container to port 8080 on the host machine
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 3.235.176.185
    depends_on:
      - serviceregistry # This service depends on serviceregistry. Start that first.
  serviceregistry:
    build: eurekaserver 
    container_name: serviceregistry
    image: hotelbookingapp/serviceregistry:1.0.0
    ports:
    - "8761:8761" # Map the exposed port 8761 on container to port 8761 on the host machine
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 3.235.176.185
networks:
  microservicesnet:
    driver: bridge
